# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 未知时间
email: unstart.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  你好吗UAU
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://n-a.date" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: NONE
github_username: unstartdev
timezone: Asia/Shanghai
google_analytics: UA-110545039-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

#paginate: 5
#paginate_path: "/page/:num/"

gitment:
  enable: true
  owner: unstartdev
  repo: unstartdev.github.io
  oauth:
    client_id: 4f2e3a545ce5cd17a494
    client_secret: 97af88a25215689997b186d418e16c38373b30d4

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
