# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: UNKNOWN date
email: admin(#)edu.n-a.date
description: >- # this means to ignore newlines until "baseurl:"
  Helowww~
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://n-a.date" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: NONE
github_username: unstartdev
timezone: Asia/Shanghai
valine:
  enabled: true
  appid: '27C1J8NnDsg7TJDXn03efOkb-MdYXbMMI'
  appkey: '3KLNAxfjACc8yPYzDsGDvxTU'
  region: 'us'
  notify: 'true'
  verify: 'true'
  placeholder: 'Touch Me!'
  avatar: 'mm'

google_analytics: UA-110545039-1
# Build settings
lang: zh
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
